### PR TITLE
Table json view

### PR DESCRIPTION
**Pull request by bwalsh**
### This PR:
* adds a json view in the table
* minimal logo
* tied to forked react component 
* the callback for TOGGLE_IN_TABLE will show/hide the property in the table
### `Also`
* on start-up a default query will be run
* on node click the default query  will be run (if necessary)

Known issue:
The callback that returns [FILTER_FOR_VALUE,FILTER_OUT_VALUE] currently simply logs to the console.   In the next phase we will turn the payload of the callback to action events to update state and UI changes

image

### CODE REVIEW

**Comment by prismofeverything** [comment]
Hey Brian, thanks for this!

Currently getting an error when trying to run this:

    utils.js:235 uncaught at fetchFacets TypeError: Cannot read property 'tableSelectedColumns' of undefined
    at http://localhost:8080/js/bundle.js:159980:43
    at Object._.pick (http://localhost:8080/js/bundle.js:52518:12)
    at Function.mapStateToProps [as mapToProps] (http://localhost:8080/js/bundle.js:159979:24)
    at mapToPropsProxy (http://localhost:8080/js/bundle.js:32307:47)
    at handleNewState (http://localhost:8080/js/bundle.js:32513:27)
    at handleSubsequentCalls (http://localhost:8080/js/bundle.js:32530:31)
    at pureFinalPropsSelector (http://localhost:8080/js/bundle.js:32535:33)
    at Object.runComponentSelector [as run] (http://localhost:8080/js/bundle.js:30553:26)
    at Connect.componentWillReceiveProps (http://localhost:8080/js/bundle.js:30677:24)
    at http://localhost:8080/js/bundle.js:24342:24

**Comment by bwalsh** [comment]
Thanks Ryan,
I'll double check this later today

**Comment by bwalsh** [comment]
I was unable to reproduce.   I'm traveling right now, lets touch base later today

**Comment by bwalsh** [comment]
@prismofeverything  Ryan: HI.  Can you re-try testing this branch?

**Comment by prismofeverything** [comment]
Hi Brian,

Just tried this again, getting this error in the console: 

    Header.js:117 Uncaught TypeError: (0 , _styles.createStyleSheet) is not a function
    at Object.<anonymous> (Header.js:117)
    at Object.<anonymous> (bundle.js:56691)
    at __webpack_require__ (bootstrap 8973d6b…:19)
    at Object.<anonymous> (App.js:3)
    at Object.<anonymous> (bundle.js:56438)
    at __webpack_require__ (bootstrap 8973d6b…:19)
    at Object.<anonymous> (router.js:4)
    at Object.<anonymous> (bundle.js:56338)
    at __webpack_require__ (bootstrap 8973d6b…:19)
    at Object.<anonymous> (index.js:6)

Which when I look in the source shows this:

    const styleSheet = createStyleSheet({
      root: {
        marginTop: 4,
        width: '100%',
      },
      flex: {
        flex: 1,
      },
    });

Not sure why that isn't a function?

Also, when I do an `npm i -S` I get a bunch of warnings like this:

    npm WARN material-ui-search-bar@1.0.0-beta.2 requires a peer of material-ui@^1.0.0 but none was installed.
    npm WARN react-json-view-callback@1.11.10 requires a peer of chai@^3.5.0 but none was installed.
    npm WARN react-json-view-callback@1.11.10 requires a peer of coveralls@^2.13.1 but none was installed.
    npm WARN react-json-view-callback@1.11.10 requires a peer of istanbul@^0.4.5 but none was installed.
    npm WARN react-json-view-callback@1.11.10 requires a peer of jsdom@^10.1.0 but none was installed.
    npm WARN react-json-view-callback@1.11.10 requires a peer of nyc@^10.3.2 but none was installed.
    npm WARN react-json-view-callback@1.11.10 requires a peer of react-test-renderer@^15.5.4 but none was installed.
    npm WARN react-json-view-callback@1.11.10 requires a peer of sinon@^2.2.0 but none was installed.
    npm WARN react-json-view-callback@1.11.10 requires a peer of webpack-bundle-size-analyzer@^2.7.0 but none was installed.

Though they don't seem to break the build. I mention it in case it is related somehow.

Any idea what's going on? Why does it work for you and not for me? I would love our environment to be generally reproducible, let's figure out how the discrepancies are even possible here.

**Comment by bwalsh** [comment]
@prismofeverything  thanks for your time.

I just checked in a change to lock down a specific version of material-ui ( they just released a new version .beta-5 a day ago )


```
index c432be2..f1a3107 100644
--- a/package.json
+++ b/package.json
@@ -33,7 +33,7 @@
   "license": "MIT",
   "dependencies": {
     "cytoscape": "^3.1.4",
-    "material-ui": "^1.0.0-beta.4",
+    "material-ui": "1.0.0-beta.4",
     "material-ui-icons": "^1.0.0-alpha.19",
```

BTW, this was the breaking change https://github.com/callemall/material-ui/pull/7740

**Comment by prismofeverything** [comment]
Ah awesome, it works now! Thanks Brian : )

I'm not seeing any other columns besides the JSON in the results table now. Is that intentional?

**Comment by bwalsh** [comment]
@prismofeverything  Also,  I've added the jsonView's peer dependencies to the project. 
As a result the npm warnings have been reduced to a mismatch from material-ui-search-bar...

```
$ npm i -S
bmeg@0.1.0 /Users/walsbr/bmeg
├── UNMET PEER DEPENDENCY material-ui@1.0.0-beta.4
└── node-pre-gyp@0.6.36

npm WARN material-ui-search-bar@1.0.0-beta.3 requires a peer of material-ui@^1.0.0 but none was installed.
```

**Comment by bwalsh** [comment]
@prismofeverything 
>I'm not seeing any other columns besides the JSON in the results table now. Is that intentional?

Yes, If you hover over a key value in the json blob, it gives the user the opportunity to build their own table.   The selected columns are then stored in  `tableFacets` in the current Query.
Ultimately, the tableFacets should be serialized along with the query.
 

image

**Comment by prismofeverything** [comment]
Understood and agreed. I love that the users have the ability to configure their own tables. Let's figure out something for people to see if it is their first using the tool as well.

**Comment by bwalsh** [comment]
image

@prismofeverything  per yesterday's conversation

**Comment by prismofeverything** [comment]
All good, thanks for taking care of all that.

**Pull request merged**
