### PR TITLE
Deployment

### PR DESCRIPTION
**Pull request by bwalsh**
This PR creates a docker-compose deployment of:
* bmeg site
* nginx google auth
* mongo
* grip
* gcsfuse

See 
https://bmeg-staging6.ddns.net

### CODE REVIEW

**Comment by kellrott** [comment]
Tested auth with https://github.com/bmeg/grip/pull/190 
👍

**Comment by bwalsh** [comment]
@kellrott , @adamstruck : fyi.  going to deploy this on bmegio.ohsu.edu.  If all ok, we should merge?

**Comment by kellrott** [comment]
👍

**Comment by adamstruck** [comment]
👍

**Comment by bwalsh** [comment]
Closing. Superseded by deploy-bmegio-jupyter

**Pull request closed without merging**
